Improved some Xfce build scripts and patch

diff --git a/003-xfce/xfce/xfconf/xfconf.SlackBuild b/003-xfce/xfce/xfconf/xfconf.SlackBuild
--- a/003-xfce/xfce/xfconf/xfconf.SlackBuild
+++ b/003-xfce/xfce/xfconf/xfconf.SlackBuild
@@ -25,6 +25,10 @@ DOWNLOADVERSION=$(curl -s https://gitlab.xfce.org/xfce/${PRGNAM}/-/tags?format=a
 		done
 	fi
 })
+if [ -z "$DOWNLOADVERSION" ]; then
+	echo "Error: cannot detect latest $PRGNAM version."
+	exit 1
+fi
 VERSION=$(echo $DOWNLOADVERSION | rev | cut -d '-' -f 1 | rev)
 wget https://gitlab.xfce.org/xfce/${PRGNAM}/-/archive/${DOWNLOADVERSION}/${PRGNAM}-${DOWNLOADVERSION}.tar.gz
 
diff --git a/003-xfce/xfce/xfdesktop/xfdesktop.SlackBuild b/003-xfce/xfce/xfdesktop/xfdesktop.SlackBuild
--- a/003-xfce/xfce/xfdesktop/xfdesktop.SlackBuild
+++ b/003-xfce/xfce/xfdesktop/xfdesktop.SlackBuild
@@ -25,6 +25,10 @@ DOWNLOADVERSION=$(curl -s https://gitlab.xfce.org/xfce/${PRGNAM}/-/tags?format=a
 		done
 	fi
 })
+if [ -z "$DOWNLOADVERSION" ]; then
+	echo "Error: cannot detect latest $PRGNAM version."
+	exit 1
+fi
 VERSION=$(echo $DOWNLOADVERSION | rev | cut -d '-' -f 1 | rev)
 wget https://gitlab.xfce.org/xfce/${PRGNAM}/-/archive/${DOWNLOADVERSION}/${PRGNAM}-${DOWNLOADVERSION}.tar.gz
 
@@ -39,6 +43,9 @@ sed -i "s|subdir('tests')|#subdir('tests')|g" meson.build
 sed -i "s|size_string = g_format_size(size)|size_string = g_format_size_full(size, G_FORMAT_SIZE_IEC_UNITS)|g" src/xfdesktop-regular-file-icon.c
 sed -i "s|size_string = g_format_size(size)|size_string = g_format_size_full(size, G_FORMAT_SIZE_IEC_UNITS)|g" src/xfdesktop-special-file-icon.c
 sed -i "s|size_string = g_format_size(size)|size_string = g_format_size_full(size, G_FORMAT_SIZE_IEC_UNITS)|g" src/xfdesktop-volume-icon.c
+grep -q "g_format_size_full(size, G_FORMAT_SIZE_IEC_UNITS)" src/xfdesktop-regular-file-icon.c
+grep -q "g_format_size_full(size, G_FORMAT_SIZE_IEC_UNITS)" src/xfdesktop-special-file-icon.c
+grep -q "g_format_size_full(size, G_FORMAT_SIZE_IEC_UNITS)" src/xfdesktop-volume-icon.c
 
 if [[ "$ALLOW_TEST" == "yes" ]]; then
 	VIDEO_BACKDROP="-Dvideo-backdrop=false"
diff --git a/003-xfce/xfce/xfwm4-gl/xfwm4-gl.SlackBuild b/003-xfce/xfce/xfwm4-gl/xfwm4-gl.SlackBuild
--- a/003-xfce/xfce/xfwm4-gl/xfwm4-gl.SlackBuild
+++ b/003-xfce/xfce/xfwm4-gl/xfwm4-gl.SlackBuild
@@ -18,6 +18,10 @@ download_master_from_github fulalas $PRGNAM main || exit 1
 cd xfwm4-gl-main
 
 VERSION=$(sed -n 's/^XDT_VERSION_INIT(\[\([^]]*\)\]\(, *\[\([^]]*\)\]\)\?).*/\1\3/p' configure.ac)
+if [ -z "$VERSION" ]; then
+	echo "Error: cannot detect $PRGNAM version."
+	exit 1
+fi
 
 CFLAGS="$GCC_CFLAGS -ffat-lto-objects -ffast-math" \
 ./autogen.sh \
