Improved build scripts

diff --git a/003-xfce/xfce/xfce4-appfinder/xfce4-appfinder.SlackBuild b/003-xfce/xfce/xfce4-appfinder/xfce4-appfinder.SlackBuild
--- a/003-xfce/xfce/xfce4-appfinder/xfce4-appfinder.SlackBuild
+++ b/003-xfce/xfce/xfce4-appfinder/xfce4-appfinder.SlackBuild
@@ -25,6 +25,10 @@ DOWNLOADVERSION=$(curl -s https://gitlab.xfce.org/xfce/${PRGNAM}/-/tags?format=a
 		done
 	fi
 })
+if [ -z "$DOWNLOADVERSION" ]; then
+	echo "Error: cannot detect latest $PRGNAM version."
+	exit 1
+fi
 VERSION=$(echo $DOWNLOADVERSION | rev | cut -d '-' -f 1 | rev)
 wget https://gitlab.xfce.org/xfce/${PRGNAM}/-/archive/${DOWNLOADVERSION}/${PRGNAM}-${DOWNLOADVERSION}.tar.gz
 
@@ -39,6 +43,8 @@ done
 # add case insensitive and contains features
 sed -i 's/xfce_appfinder_model_fuzzy_match (item->command, string);/strcasestr(item->command, string) != 0;/g' src/appfinder-model.c
 sed -i 's/xfce_appfinder_model_fuzzy_match (item->key, string_casefold);/strcasestr(item->key, string_casefold) != 0;/g' src/appfinder-model.c
+grep -q 'strcasestr(item->command, string)' src/appfinder-model.c
+grep -q 'strcasestr(item->key, string_casefold)' src/appfinder-model.c
 
 if [ -f meson.build ]; then
 	mkdir meson-build && cd meson-build
diff --git a/003-xfce/xfce/xfce4-panel/xfce4-panel.SlackBuild b/003-xfce/xfce/xfce4-panel/xfce4-panel.SlackBuild
--- a/003-xfce/xfce/xfce4-panel/xfce4-panel.SlackBuild
+++ b/003-xfce/xfce/xfce4-panel/xfce4-panel.SlackBuild
@@ -25,6 +25,10 @@ DOWNLOADVERSION=$(curl -s https://gitlab.xfce.org/xfce/${PRGNAM}/-/tags?format=a
 		done
 	fi
 })
+if [ -z "$DOWNLOADVERSION" ]; then
+	echo "Error: cannot detect latest $PRGNAM version."
+	exit 1
+fi
 VERSION=$(echo $DOWNLOADVERSION | rev | cut -d '-' -f 1 | rev)
 wget https://gitlab.xfce.org/xfce/${PRGNAM}/-/archive/${DOWNLOADVERSION}/${PRGNAM}-${DOWNLOADVERSION}.tar.gz
 
@@ -36,6 +40,9 @@ sed -i "s|subdir('docs'|#subdir('docs'|g" meson.build
 sed -i "s|define DEFAULT_POPDOWN_DELAY (350)|define DEFAULT_POPDOWN_DELAY (10)|g" panel/panel-window.c
 sed -i "s|define DEFAULT_POPDOWN_SPEED (25)|define DEFAULT_POPDOWN_SPEED (10)|g" panel/panel-window.c
 sed -i "s|define DEFAULT_POPUP_DELAY (225)|define DEFAULT_POPUP_DELAY (10)|g" panel/panel-window.c
+grep -q "define DEFAULT_POPDOWN_DELAY (10)" panel/panel-window.c
+grep -q "define DEFAULT_POPDOWN_SPEED (10)" panel/panel-window.c
+grep -q "define DEFAULT_POPUP_DELAY (10)" panel/panel-window.c
 
 mkdir meson-build && cd meson-build
 CFLAGS="$GCC_CFLAGS" \
diff --git a/003-xfce/xfce/xfce4-pulseaudio-plugin/xfce4-pulseaudio-plugin.SlackBuild b/003-xfce/xfce/xfce4-pulseaudio-plugin/xfce4-pulseaudio-plugin.SlackBuild
--- a/003-xfce/xfce/xfce4-pulseaudio-plugin/xfce4-pulseaudio-plugin.SlackBuild
+++ b/003-xfce/xfce/xfce4-pulseaudio-plugin/xfce4-pulseaudio-plugin.SlackBuild
@@ -13,6 +13,10 @@ mkdir -p $TMP $PKG
 cd $TMP
 
 DOWNLOADVERSION=$(curl -s https://gitlab.xfce.org/panel-plugins/${PRGNAM}/-/tags?format=atom | grep -oPm 20 '(?<= <title>)[^<]+' | grep -v pre | sort -Vr | head -1)
+if [ -z "$DOWNLOADVERSION" ]; then
+	echo "Error: cannot detect latest $PRGNAM version."
+	exit 1
+fi
 VERSION=$(echo $DOWNLOADVERSION | rev | cut -d '-' -f 1 | rev)
 wget https://gitlab.xfce.org/panel-plugins/${PRGNAM}/-/archive/${DOWNLOADVERSION}/${PRGNAM}-${DOWNLOADVERSION}.tar.gz
 
@@ -21,6 +25,8 @@ cd $PRGNAM-$DOWNLOADVERSION
 
 sed -i "s|reconnect in 5 seconds|reconnect in 1 second|g" panel-plugin/pulseaudio-volume.c
 sed -i "s|(5, pulseaudio_volume_reconnect_timeout, volume)|(1, pulseaudio_volume_reconnect_timeout, volume)|g" panel-plugin/pulseaudio-volume.c
+grep -q "reconnect in 1 second" panel-plugin/pulseaudio-volume.c
+grep -q "(1, pulseaudio_volume_reconnect_timeout, volume)" panel-plugin/pulseaudio-volume.c
 
 mkdir meson-build && cd meson-build
 CFLAGS="$GCC_CFLAGS" \
diff --git a/003-xfce/xfce/xfce4-session/xfce4-session.SlackBuild b/003-xfce/xfce/xfce4-session/xfce4-session.SlackBuild
--- a/003-xfce/xfce/xfce4-session/xfce4-session.SlackBuild
+++ b/003-xfce/xfce/xfce4-session/xfce4-session.SlackBuild
@@ -25,6 +25,10 @@ DOWNLOADVERSION=$(curl -s https://gitlab.xfce.org/xfce/${PRGNAM}/-/tags?format=a
 		done
 	fi
 })
+if [ -z "$DOWNLOADVERSION" ]; then
+	echo "Error: cannot detect latest $PRGNAM version."
+	exit 1
+fi
 VERSION=$(echo $DOWNLOADVERSION | rev | cut -d '-' -f 1 | rev)
 wget https://gitlab.xfce.org/xfce/${PRGNAM}/-/archive/${DOWNLOADVERSION}/${PRGNAM}-${DOWNLOADVERSION}.tar.gz
 
@@ -59,7 +63,7 @@ fi
 find $PKG -type f -name "*.la" -delete
 
 # don't ship the xscreensaver autostart file
-rm -fr $PKG/etc/xdg/autostart
+rm -f $PKG/etc/xdg/autostart/xscreensaver.desktop
 
 install -Dm755 "$CWD/xinitrc.xfce" $PKG/etc/X11/xinit/xinitrc.xfce
 cd $PKG/etc/X11/xinit/
diff --git a/003-xfce/xfce/xfce4-terminal/xfce4-terminal.SlackBuild b/003-xfce/xfce/xfce4-terminal/xfce4-terminal.SlackBuild
--- a/003-xfce/xfce/xfce4-terminal/xfce4-terminal.SlackBuild
+++ b/003-xfce/xfce/xfce4-terminal/xfce4-terminal.SlackBuild
@@ -13,6 +13,10 @@ mkdir -p $TMP $PKG
 cd $TMP
 
 DOWNLOADVERSION=$(curl -s https://gitlab.xfce.org/apps/${PRGNAM}/-/tags?format=atom | grep -oPm 20 '(?<= <title>)[^<]+' | grep -v pre | sort -Vr | head -1)
+if [ -z "$DOWNLOADVERSION" ]; then
+	echo "Error: cannot detect latest $PRGNAM version."
+	exit 1
+fi
 VERSION=$(echo $DOWNLOADVERSION | rev | cut -d '-' -f 1 | rev)
 wget https://gitlab.xfce.org/apps/${PRGNAM}/-/archive/${DOWNLOADVERSION}/${PRGNAM}-${DOWNLOADVERSION}.tar.gz
 
@@ -20,6 +24,7 @@ tar xf $PRGNAM-$DOWNLOADVERSION.tar.?z*
 cd $PRGNAM-$DOWNLOADVERSION
 
 sed -i "s|subdir('doc')|#subdir('doc')|g" meson.build
+grep -q "#subdir('doc')" meson.build
 
 mkdir meson-build && cd meson-build
 CFLAGS="$GCC_CFLAGS" \
