Download the tarball instead of git clone -- this improves download time

diff --git a/003-lxde/lxde/lxpanel/lxpanel.SlackBuild b/003-lxde/lxde/lxpanel/lxpanel.SlackBuild
--- a/003-lxde/lxde/lxpanel/lxpanel.SlackBuild
+++ b/003-lxde/lxde/lxpanel/lxpanel.SlackBuild
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+source "$BUILDER_UTILS_PATH/latest-from-github.sh"
+
 PRGNAM=lxpanel
 
 CWD=$(dirname "$0")
@@ -12,9 +14,14 @@ set -e
 mkdir -p $TMP $PKG
 cd $TMP
 
-git clone https://github.com/lxde/${PRGNAM}
-cd ${PRGNAM}
-VERSION=`git describe | cut -d- -f1`
+download_master_from_github lxde ${PRGNAM} || exit 1
+cd ${PRGNAM}-master || exit 1
+
+VERSION=$(grep -m1 -oP 'AC_INIT\(\s*\[?[^],]+\]?\s*,\s*\[?\K[^],\]]+' configure.ac)
+if [ -z "$VERSION" ]; then
+	echo "Error: cannot detect $PRGNAM version."
+	exit 1
+fi
 
 for i in $CWD/*.patch; do
 	patch -p0 < $i;
